# Config file used for internal tools at Auctionet

dependencies:
  node: "6.9.2"
  phantomjs: "2.1.1"

docker_services:
  postgres:
    image: "postgres:9.4.17"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/review/postgres:/var/lib/postgresql/data"
